name: Deploy to GitHub Pages

on:
  push:
    branches:
      - page # Defina aqui a branch de origem que deseja monitorar para implantação (pode ser outra branch que você usa como base).

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build your site # Substitua este comando pelo comando para construir seu site estático, se necessário.
        run: |
          # Exemplo para um site construído com npm e React
          yarn install
          yarn run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SECRET }}
          publish_dir: ./build # Substitua este caminho pelo diretório de saída do build do seu site estático
