name: Deploy Environments

on:
  push:
    branches:
      - "*"

jobs:
  deploy:
    name: Deploy to Environment
    runs-on: ubuntu-latest
    # enviroment: gh-pages

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Environment
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.SECRET }}
          publish-dir: ./build # Diretório onde está o site estático gerado
          publish-branch: ${{ github.ref_slug }}-env # Nome da branch do ambiente
