name: Deploy Storybook

on:
  push:
    branches:
      - pag2

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: pag2
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      - name: Build Storybook
        run: yarn build

      - name: Create versioned directory
        run: mkdir "./build/1"

      - name: Copy build to versioned directory
        run: cp -r "./build" "./build/1"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: "./build/1"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
